# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: aec7624c3fdc6880386158ac8ba4d938cd1b72f0
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: aec7624c3fdc6880386158ac8ba4d938cd1b72f0