# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 70f2717e4342d0a700508c3dd8e52e1cc7a68af1
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 70f2717e4342d0a700508c3dd8e52e1cc7a68af1