# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: d7a784022f6ae20532185fc8fe7e604e75be179d
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: d7a784022f6ae20532185fc8fe7e604e75be179d