# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 00725f837199f15a049390cf949e43f5157d2702
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 00725f837199f15a049390cf949e43f5157d2702