# backend:
#   image:
#     repository: jaimehenao8126/globant-frontend
#     tag: e9db64ebb4a9e9140b8c58165159cb363ea60007
# frontend:
#   image:
#     repository: jaimehenao8126/globant-frontend
#     tag: e9db64ebb4a9e9140b8c58165159cb363ea60007

# values.yaml

replicaCount: 1

backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: e9db64ebb4a9e9140b8c58165159cb363ea60007

frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: e9db64ebb4a9e9140b8c58165159cb363ea60007

service:
  type: ClusterIP
  port: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1