# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: ffe44c72886dd3fb3046e9d603ad93d52c436d07
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: ffe44c72886dd3fb3046e9d603ad93d52c436d07