# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: my-docker-account/globant-backend
    tag: latest
frontend:
  image:
    repository: my-docker-account/globant-frontend
    tag: latest