# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: f588d802d8e4210204056b9ce164f4523f8a37de
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: f588d802d8e4210204056b9ce164f4523f8a37de