# frontend:
#   image: jaimehenao8126/frontend:latest

# backend:
#   image: jaimehenao8126/backend:latest

# values.yaml
backend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 23d826777e91b2a864419bb557d8363441413918
frontend:
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 23d826777e91b2a864419bb557d8363441413918